version: '3'
services:
    web:
        build: ./Dockerfiles/web/
        ports: 
            - '34100:3410'
        privileged: true
        volumes: .:/app
        tty: true
        stdin_open: true
        command: /bin/sh
        container_name: todo_app_web
    # api:
    #     build: ./Dockerfiles/api
    #     working_dir: /go/src/work/src
    #     ports: 
    #         - '13240:1324'
    #     depends_on: 
    #         - db
    #     volumes: 
    #         - .:/go/src/work
    #     command: sleep infinity
    #     restart: always
    #     container_name: api-todo-app
    # db:
    #     image: mysql:latest
    #     command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    #     volumes:
    #         - "./initdb.d:/docker-entrypoint-initdb.d"
    #     ports: '33100:3310'
    #     restart: always
    #     expose: 
    #         - '3310'
    #     environment:
    #         MYSQL_ROOT_PASSWORD: root
    #     # name container
    #     container_name: db-todo-app