version: '3'
services:
    web:
        build: ./Dockerfiles/web/
        # ports: 
        #     - '34100:9050'
        privileged: true
        volumes:
            - .:/app
        tty: true
        stdin_open: true
        container_name: todo_app_web